export const DEMO_LANDLORD_ID = 'demo-landlord-001'

export const getInitialData = (landlordId = DEMO_LANDLORD_ID) => {
  const properties = [
    {
      id: 'prop-1',
      landlord_id: landlordId,
      name: 'Highland Oak Apartments',
      address: '1240 Highland Terrace',
      city: 'Austin',
      state: 'TX',
      zip_code: '78704',
      property_type: 'Apartment',
      notes: 'Built in 2018, modern 4-unit building with gated parking.',
      created_at: '2025-01-15T08:00:00Z',
      updated_at: '2025-01-15T08:00:00Z',
    },
    {
      id: 'prop-2',
      landlord_id: landlordId,
      name: 'Maple Street Duplex',
      address: '842 Maple Ave',
      city: 'Austin',
      state: 'TX',
      zip_code: '78702',
      property_type: 'Multi-Family',
      notes: 'Craftsman style duplex with private backyards and solar panels.',
      created_at: '2025-02-10T10:00:00Z',
      updated_at: '2025-02-10T10:00:00Z',
    },
    {
      id: 'prop-3',
      landlord_id: landlordId,
      name: 'Sunset Ridge Cottage',
      address: '310 Sunset Ridge Rd',
      city: 'Austin',
      state: 'TX',
      zip_code: '78746',
      property_type: 'Single Family',
      notes: '3-bedroom ranch with updated kitchen and scenic views.',
      created_at: '2025-03-01T12:00:00Z',
      updated_at: '2025-03-01T12:00:00Z',
    },
  ]

  const units = [
    {
      id: 'unit-101',
      landlord_id: landlordId,
      property_id: 'prop-1',
      unit_number: 'Apt 101',
      monthly_rent: 1450,
      bedrooms: 1,
      bathrooms: 1.0,
      is_occupied: true,
      notes: 'Ground floor unit with patio access.',
      created_at: '2025-01-15T08:00:00Z',
      updated_at: '2025-01-15T08:00:00Z',
    },
    {
      id: 'unit-102',
      landlord_id: landlordId,
      property_id: 'prop-1',
      unit_number: 'Apt 102',
      monthly_rent: 1600,
      bedrooms: 2,
      bathrooms: 1.5,
      is_occupied: true,
      notes: 'Upstairs corner unit with balcony.',
      created_at: '2025-01-15T08:00:00Z',
      updated_at: '2025-01-15T08:00:00Z',
    },
    {
      id: 'unit-201',
      landlord_id: landlordId,
      property_id: 'prop-1',
      unit_number: 'Apt 201',
      monthly_rent: 1750,
      bedrooms: 2,
      bathrooms: 2.0,
      is_occupied: false,
      notes: 'Recently painted, new hardwood flooring.',
      created_at: '2025-01-15T08:00:00Z',
      updated_at: '2025-01-15T08:00:00Z',
    },
    {
      id: 'unit-maple-a',
      landlord_id: landlordId,
      property_id: 'prop-2',
      unit_number: 'Unit A (Front)',
      monthly_rent: 2100,
      bedrooms: 3,
      bathrooms: 2.0,
      is_occupied: true,
      notes: 'Attached 1-car garage.',
      created_at: '2025-02-10T10:00:00Z',
      updated_at: '2025-02-10T10:00:00Z',
    },
    {
      id: 'unit-maple-b',
      landlord_id: landlordId,
      property_id: 'prop-2',
      unit_number: 'Unit B (Back)',
      monthly_rent: 1950,
      bedrooms: 2,
      bathrooms: 2.0,
      is_occupied: true,
      notes: 'Includes fenced back yard and shed.',
      created_at: '2025-02-10T10:00:00Z',
      updated_at: '2025-02-10T10:00:00Z',
    },
    {
      id: 'unit-sunset-1',
      landlord_id: landlordId,
      property_id: 'prop-3',
      unit_number: 'Main Residence',
      monthly_rent: 2800,
      bedrooms: 3,
      bathrooms: 2.5,
      is_occupied: true,
      notes: 'Single family home with pool and deck.',
      created_at: '2025-03-01T12:00:00Z',
      updated_at: '2025-03-01T12:00:00Z',
    },
  ]

  const tenants = [
    {
      id: 'tenant-1',
      landlord_id: landlordId,
      property_id: 'prop-1',
      unit_id: 'unit-101',
      full_name: 'Sarah Jenkins',
      email: 'sarah.jenkins@example.com',
      phone: '(512) 555-0143',
      lease_start_date: '2025-06-01',
      lease_end_date: '2027-05-31',
      monthly_rent: 1450,
      rent_due_day: 1,
      emergency_contact: 'Mark Jenkins (Brother) - (512) 555-0199',
      notes: 'Software engineer at tech startup. Always reliable.',
      is_active: true,
      created_at: '2025-05-20T10:00:00Z',
      updated_at: '2025-05-20T10:00:00Z',
    },
    {
      id: 'tenant-2',
      landlord_id: landlordId,
      property_id: 'prop-1',
      unit_id: 'unit-102',
      full_name: 'Marcus Vance',
      email: 'm.vance@example.com',
      phone: '(512) 555-0182',
      lease_start_date: '2025-08-01',
      lease_end_date: '2026-11-30',
      monthly_rent: 1600,
      rent_due_day: 5,
      emergency_contact: 'Lisa Vance (Mother) - (512) 555-0128',
      notes: 'Works remotely. Has a small beagle registered.',
      is_active: true,
      created_at: '2025-07-15T11:00:00Z',
      updated_at: '2025-07-15T11:00:00Z',
    },
    {
      id: 'tenant-3',
      landlord_id: landlordId,
      property_id: 'prop-2',
      unit_id: 'unit-maple-a',
      full_name: 'Elena Rostova',
      email: 'elena.rostova@example.com',
      phone: '(512) 555-0199',
      lease_start_date: '2025-03-01',
      lease_end_date: '2027-02-28',
      monthly_rent: 2100,
      rent_due_day: 1,
      emergency_contact: 'Dmitri Rostova - (512) 555-0177',
      notes: 'Graphic designer. Prefers communication via text.',
      is_active: true,
      created_at: '2025-02-20T14:00:00Z',
      updated_at: '2025-02-20T14:00:00Z',
    },
    {
      id: 'tenant-4',
      landlord_id: landlordId,
      property_id: 'prop-2',
      unit_id: 'unit-maple-b',
      full_name: 'Liam & Sophia Chen',
      email: 'chen.family@example.com',
      phone: '(512) 555-0164',
      lease_start_date: '2025-04-01',
      lease_end_date: '2027-03-31',
      monthly_rent: 1950,
      rent_due_day: 10,
      emergency_contact: 'Helen Chen (Mother) - (512) 555-0112',
      notes: 'Young couple, requested EV charger installation approval.',
      is_active: true,
      created_at: '2025-03-15T09:00:00Z',
      updated_at: '2025-03-15T09:00:00Z',
    },
    {
      id: 'tenant-5',
      landlord_id: landlordId,
      property_id: 'prop-3',
      unit_id: 'unit-sunset-1',
      full_name: 'Dr. Julian Hayes',
      email: 'j.hayes@example.org',
      phone: '(512) 555-0111',
      lease_start_date: '2025-01-01',
      lease_end_date: '2026-12-31',
      monthly_rent: 2800,
      rent_due_day: 1,
      emergency_contact: 'Dr. Rachel Hayes - (512) 555-0133',
      notes: 'Surgeon at St. David Medical Center. Long-term tenant.',
      is_active: true,
      created_at: '2024-12-15T16:00:00Z',
      updated_at: '2024-12-15T16:00:00Z',
    },
  ]

  // Calculate current and previous month keys
  const now = new Date()
  const curY = now.getFullYear()
  const curM = String(now.getMonth() + 1).padStart(2, '0')
  const currentMonthKey = `${curY}-${curM}`

  const prevDate = new Date(now.getFullYear(), now.getMonth() - 1, 1)
  const prevY = prevDate.getFullYear()
  const prevM = String(prevDate.getMonth() + 1).padStart(2, '0')
  const prevMonthKey = `${prevY}-${prevM}`

  const rent_payments = [
    // Current Month Payments
    {
      id: 'pay-1',
      landlord_id: landlordId,
      tenant_id: 'tenant-1',
      property_id: 'prop-1',
      unit_id: 'unit-101',
      month_year: currentMonthKey,
      amount: 1450,
      payment_date: `${curY}-${curM}-01`,
      due_date: `${curY}-${curM}-01`,
      status: 'Paid',
      payment_method: 'Bank Transfer',
      reference_note: 'Direct Deposit Ref #ACH-98231',
      created_at: `${curY}-${curM}-01T09:30:00Z`,
      updated_at: `${curY}-${curM}-01T09:30:00Z`,
    },
    {
      id: 'pay-2',
      landlord_id: landlordId,
      tenant_id: 'tenant-2',
      property_id: 'prop-1',
      unit_id: 'unit-102',
      month_year: currentMonthKey,
      amount: 1600,
      payment_date: `${curY}-${curM}-03`,
      due_date: `${curY}-${curM}-05`,
      status: 'Paid',
      payment_method: 'Zelle',
      reference_note: 'Zelle transfer confirmation #ZEL-48210',
      created_at: `${curY}-${curM}-03T14:15:00Z`,
      updated_at: `${curY}-${curM}-03T14:15:00Z`,
    },
    {
      id: 'pay-3',
      landlord_id: landlordId,
      tenant_id: 'tenant-5',
      property_id: 'prop-3',
      unit_id: 'unit-sunset-1',
      month_year: currentMonthKey,
      amount: 2800,
      payment_date: `${curY}-${curM}-01`,
      due_date: `${curY}-${curM}-01`,
      status: 'Paid',
      payment_method: 'Bank Transfer',
      reference_note: 'Auto ACH payment',
      created_at: `${curY}-${curM}-01T08:00:00Z`,
      updated_at: `${curY}-${curM}-01T08:00:00Z`,
    },
    {
      id: 'pay-4',
      landlord_id: landlordId,
      tenant_id: 'tenant-3', // Elena - Overdue
      property_id: 'prop-2',
      unit_id: 'unit-maple-a',
      month_year: currentMonthKey,
      amount: 2100,
      payment_date: null,
      due_date: `${curY}-${curM}-01`,
      status: 'Overdue',
      payment_method: 'Pending',
      reference_note: 'Sent friendly email reminder on 2nd',
      created_at: `${curY}-${curM}-01T00:00:00Z`,
      updated_at: `${curY}-${curM}-01T00:00:00Z`,
    },
    {
      id: 'pay-5',
      landlord_id: landlordId,
      tenant_id: 'tenant-4', // Liam & Sophia - Pending due on 10th
      property_id: 'prop-2',
      unit_id: 'unit-maple-b',
      month_year: currentMonthKey,
      amount: 1950,
      payment_date: null,
      due_date: `${curY}-${curM}-10`,
      status: 'Pending',
      payment_method: 'Bank Transfer',
      reference_note: 'Regular due date on 10th',
      created_at: `${curY}-${curM}-01T00:00:00Z`,
      updated_at: `${curY}-${curM}-01T00:00:00Z`,
    },
    // Previous Month Payments (All Paid)
    {
      id: 'pay-prev-1',
      landlord_id: landlordId,
      tenant_id: 'tenant-1',
      property_id: 'prop-1',
      unit_id: 'unit-101',
      month_year: prevMonthKey,
      amount: 1450,
      payment_date: `${prevY}-${prevM}-01`,
      due_date: `${prevY}-${prevM}-01`,
      status: 'Paid',
      payment_method: 'Bank Transfer',
      reference_note: 'ACH Confirmation',
      created_at: `${prevY}-${prevM}-01T10:00:00Z`,
      updated_at: `${prevY}-${prevM}-01T10:00:00Z`,
    },
    {
      id: 'pay-prev-2',
      landlord_id: landlordId,
      tenant_id: 'tenant-2',
      property_id: 'prop-1',
      unit_id: 'unit-102',
      month_year: prevMonthKey,
      amount: 1600,
      payment_date: `${prevY}-${prevM}-04`,
      due_date: `${prevY}-${prevM}-05`,
      status: 'Paid',
      payment_method: 'Zelle',
      reference_note: 'Zelle transfer',
      created_at: `${prevY}-${prevM}-04T12:00:00Z`,
      updated_at: `${prevY}-${prevM}-04T12:00:00Z`,
    },
    {
      id: 'pay-prev-3',
      landlord_id: landlordId,
      tenant_id: 'tenant-3',
      property_id: 'prop-2',
      unit_id: 'unit-maple-a',
      month_year: prevMonthKey,
      amount: 2100,
      payment_date: `${prevY}-${prevM}-02`,
      due_date: `${prevY}-${prevM}-01`,
      status: 'Paid',
      payment_method: 'Check',
      reference_note: 'Check #1042',
      created_at: `${prevY}-${prevM}-02T16:00:00Z`,
      updated_at: `${prevY}-${prevM}-02T16:00:00Z`,
    },
    {
      id: 'pay-prev-4',
      landlord_id: landlordId,
      tenant_id: 'tenant-4',
      property_id: 'prop-2',
      unit_id: 'unit-maple-b',
      month_year: prevMonthKey,
      amount: 1950,
      payment_date: `${prevY}-${prevM}-09`,
      due_date: `${prevY}-${prevM}-10`,
      status: 'Paid',
      payment_method: 'Bank Transfer',
      reference_note: 'Online transfer',
      created_at: `${prevY}-${prevM}-09T11:00:00Z`,
      updated_at: `${prevY}-${prevM}-09T11:00:00Z`,
    },
    {
      id: 'pay-prev-5',
      landlord_id: landlordId,
      tenant_id: 'tenant-5',
      property_id: 'prop-3',
      unit_id: 'unit-sunset-1',
      month_year: prevMonthKey,
      amount: 2800,
      payment_date: `${prevY}-${prevM}-01`,
      due_date: `${prevY}-${prevM}-01`,
      status: 'Paid',
      payment_method: 'Bank Transfer',
      reference_note: 'ACH automatic',
      created_at: `${prevY}-${prevM}-01T08:00:00Z`,
      updated_at: `${prevY}-${prevM}-01T08:00:00Z`,
    },
  ]

  const profile = {
    id: landlordId,
    email: 'landlord@renttrack.io',
    full_name: 'David Reynolds',
    phone: '(512) 555-8290',
    company_name: 'Reynolds Property Management LLC',
    currency: '$',
    date_format: 'YYYY-MM-DD',
  }

  return {
    profile,
    properties,
    units,
    tenants,
    rent_payments,
  }
}
